- name: Setup macOS system - Work
  hosts: macos
  vars:
    hostname: Twoson
    path_wallpaper: /System/Library/Desktop Pictures/Solid Colors/Stone.png
  roles:
    - common
    - macos
    - macos_work
    # - common_nvim
    # - common_nvim_work
    # - common_post
